- name: Install PostgreSQL
  apt:
    package: "{{ item }}"
    state: present
  with_items:
    - postgresql
    - python-psycopg2

- name: Accept connections from anywhere
  lineinfile:
    dest: /etc/postgresql/9.5/main/postgresql.conf
    regexp: ^#?listen_addresses
    line: listen_addresses = '*'
    state: present
  notify: Restart PostgreSQL

- name: Allow connecting from anywhere
  lineinfile:
    dest: /etc/postgresql/9.5/main/pg_hba.conf
    line: host all all 0.0.0.0/0 md5
    state: present
  notify: Restart PostgreSQL

- name: Create user
  postgresql_user:
    name: "{{ postgresql_user }}"
    password: "{{ postgresql_password }}"
    role_attr_flags: SUPERUSER
    state: present
  become_user: postgres

- name: Create database
  postgresql_db:
    name: "{{ postgresql_name }}"
    owner: "{{ postgresql_user }}"
    state: present
  become_user: postgres
